/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Calculadora de Índice de Masa Corporal (IMC).
 * Esta clase representa la ventana principal de la calculadora.
 * Yo me encargué de completar la lógica de diagnóstico y los colores
 * según la tabla de clasificación del IMC proporcionada por el profesor.
 *
 * @author achermes
 * Completado por: Eider David Pérez Quevedo
 */
public class CalculadoraIMC extends javax.swing.JFrame {

    // Mi logger para registrar errores en la consola de NetBeans
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(CalculadoraIMC.class.getName());

    /**
     * Creo el formulario de la calculadora IMC e inicializo sus componentes.
     */
    public CalculadoraIMC() {
        initComponents();
        // Yo centro la ventana en la pantalla al abrirla
        setLocationRelativeTo(null);
    }

    /**
     * Este método fue generado automáticamente por el editor de formularios de NetBeans.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pesoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        alturaText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        edadText = new javax.swing.JTextField();
        jLabelEdadUnidad = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imcLabel = new javax.swing.JLabel();
        // Yo agrego el label de diagnóstico para mostrar la clasificación del IMC
        diagnosticoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setTitle("Calculadora IMC");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                "/app/weight_fat_body_overweight_unhealthy_obesity_diet_health_belly_icon_133507.png"))); // NOI18N

        jLabel2.setText("Peso");
        jLabel3.setText("(kg)");
        jLabel4.setText("Altura");
        jLabel5.setText("(cm)");
        jLabelEdad.setText("Edad");
        jLabelEdadUnidad.setText("(años)");

        jButton1.setText(":: Calcular ::");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        // Yo configuro el label del IMC con fuente grande y negrita para que sea visible
        imcLabel.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        imcLabel.setText("--");

        // Yo configuro el label de diagnóstico: negrita, centrado y con borde redondeado
        diagnosticoLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        diagnosticoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diagnosticoLabel.setText("Ingresa tu peso, altura y edad");
        diagnosticoLabel.setOpaque(true);
        diagnosticoLabel.setBackground(new java.awt.Color(220, 220, 220));
        diagnosticoLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEdad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pesoText, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(alturaText)
                    .addComponent(edadText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabelEdadUnidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imcLabel)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    // Yo agrego el label de diagnóstico centrado debajo del botón calcular
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(diagnosticoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(alturaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        // Yo agrego la fila de edad justo debajo de la fila de altura
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEdad)
                            .addComponent(edadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEdadUnidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imcLabel)
                        .addGap(26, 26, 26)))
                .addComponent(jButton1)
                // Yo dejo un espacio y luego muestro el diagnóstico debajo del botón
                .addGap(14, 14, 14)
                .addComponent(diagnosticoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Yo manejo el evento del botón "Calcular".
     * Valido las entradas, calculo el IMC y muestro el diagnóstico con su color correspondiente.
     *
     * @param evt El evento de acción generado al hacer clic en el botón.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Yo valido que los campos no estén vacíos antes de procesar
        if (pesoText.getText().trim().isEmpty() || alturaText.getText().trim().isEmpty() || edadText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor ingresa el peso, la altura y la edad.",
                    "Campos vacíos",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            // Yo convierto los valores ingresados a tipo Double/int para poder operar con ellos
            double peso = Double.parseDouble(pesoText.getText().trim().replace(",", "."));
            double altura = Double.parseDouble(alturaText.getText().trim().replace(",", "."));
            int edad = Integer.parseInt(edadText.getText().trim());

            // Yo valido que los valores sean positivos y tengan sentido
            if (peso <= 0 || altura <= 0 || edad <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "El peso, la altura y la edad deben ser valores positivos.",
                        "Valores inválidos",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // Yo valido rangos razonables para evitar errores de digitación
            if (peso > 500) {
                JOptionPane.showMessageDialog(this, "El peso ingresado parece muy alto. Verifica el valor (máx. 500 kg).", "Valor fuera de rango", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (altura > 300) {
                JOptionPane.showMessageDialog(this, "La altura ingresada parece muy alta. Verifica el valor (máx. 300 cm).", "Valor fuera de rango", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (edad > 130) {
                JOptionPane.showMessageDialog(this, "La edad ingresada parece muy alta. Verifica el valor (máx. 130 años).", "Valor fuera de rango", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Yo convierto la altura de centímetros a metros para la fórmula del IMC
            double alturaEnMetros = altura / 100;

            // Yo calculo el IMC usando la fórmula: peso / (altura en metros)²
            double imc = peso / (alturaEnMetros * alturaEnMetros);

            // Yo muestro el resultado del IMC con dos decimales en el label grande
            imcLabel.setText(String.format("%.2f", imc));

            // Yo llamo a mi método de diagnóstico para clasificar el resultado y aplicar el color
            mostrarDiagnostico(imc);

        } catch (NumberFormatException e) {
            // Yo capturo el error si el usuario ingresa letras u otros caracteres no numéricos
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor ingresa solo valores numéricos válidos.\nUsa punto o coma como separador decimal.",
                    "Error de formato",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Yo clasifico el IMC calculado y actualizo el label de diagnóstico
     * con el texto y el color de fondo correspondiente según la tabla oficial.
     *
     * Colores basados en la imagen de clasificación del IMC:
     * - Bajo Peso     → Turquesa/Cian   (#4DD9D5)  → IMC < 18.5
     * - Peso Normal   → Verde claro     (#9DC95A)  → IMC 18.5 – 24.9
     * - Sobrepeso     → Amarillo        (#F5D76E)  → IMC 25 – 29.9
     * - Obesidad T1   → Naranja claro   (#F0A030)  → IMC 30 – 34.9
     * - Obesidad T2   → Naranja oscuro  (#E87820)  → IMC 35 – 39.9
     * - Obesidad T3   → Rojo            (#D93B3B)  → IMC ≥ 40
     *
     * @param imc El valor del IMC ya calculado.
     */
    private void mostrarDiagnostico(double imc) {

        String diagnostico;
        Color colorFondo;
        Color colorTexto = new Color(50, 50, 50); // Yo uso texto oscuro por defecto para legibilidad

        if (imc < 18.5) {
            // Yo identifico bajo peso con el color turquesa/cian de la tabla
            diagnostico = "BAJO PESO";
            colorFondo = new Color(77, 217, 213);    // Turquesa

        } else if (imc < 25.0) {
            // Yo identifico peso normal con el color verde claro
            diagnostico = "PESO NORMAL";
            colorFondo = new Color(157, 201, 90);    // Verde claro

        } else if (imc < 30.0) {
            // Yo identifico sobrepeso con el color amarillo
            diagnostico = "SOBREPESO";
            colorFondo = new Color(245, 215, 110);   // Amarillo

        } else if (imc < 35.0) {
            // Yo identifico obesidad tipo 1 con naranja claro
            diagnostico = "OBESIDAD TIPO 1";
            colorFondo = new Color(240, 160, 48);    // Naranja claro
            colorTexto = Color.WHITE;                // Uso texto blanco para mejor contraste

        } else if (imc < 40.0) {
            // Yo identifico obesidad tipo 2 con naranja oscuro
            diagnostico = "OBESIDAD TIPO 2";
            colorFondo = new Color(232, 120, 32);    // Naranja oscuro
            colorTexto = Color.WHITE;

        } else {
            // Yo identifico obesidad tipo 3 (mórbida) con rojo
            diagnostico = "OBESIDAD TIPO 3";
            colorFondo = new Color(217, 59, 59);     // Rojo
            colorTexto = Color.WHITE;
        }

        // Yo actualizo el label con el diagnóstico, el color de fondo y el color de texto
        diagnosticoLabel.setText(diagnostico);
        diagnosticoLabel.setBackground(colorFondo);
        diagnosticoLabel.setForeground(colorTexto);

        // Yo fuerzo el repintado de la interfaz para que los cambios se vean de inmediato
        diagnosticoLabel.repaint();
    }

    /**
     * Yo inicio la aplicación configurando el Look and Feel Nimbus para una mejor apariencia.
     *
     * @param args Argumentos de línea de comandos (no se usan en esta aplicación).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Yo creo y muestro el formulario de la calculadora en el hilo de eventos de Swing */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraIMC().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alturaText;
    // Yo agrego el label de diagnóstico a la sección de variables del formulario
    private javax.swing.JLabel diagnosticoLabel;
    private javax.swing.JTextField edadText;
    private javax.swing.JLabel imcLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEdadUnidad;
    private javax.swing.JTextField pesoText;
    // End of variables declaration//GEN-END:variables
}

