/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import javax.swing.JOptionPane;

/**
 * Ventana de inicio de la aplicación Calculadora IMC.
 * Yo utilizo esta clase como pantalla de bienvenida que le da acceso
 * al usuario a la ventana principal de la calculadora.
 *
 * @author achermes
 * Completado por: Eider David Pérez Quevedo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    // Mi logger para registrar posibles errores en esta ventana
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Yo creo la ventana principal e inicializo todos sus componentes visuales.
     */
    public VentanaPrincipal() {
        initComponents();
        // Yo muestro mi nombre como estudiante en el label inferior de la ventana
        jLabelNombre.setText("Eider David Pérez Quevedo");
        // Yo centro la ventana en pantalla para una mejor presentación
        setLocationRelativeTo(null);
        setTitle("Calculadora IMC - Inicio");
    }

    /**
     * Este método fue generado automáticamente por el editor de formularios de NetBeans.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clickJButton = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        clickJButton.setText("Calculadora IMC");
        clickJButton.addActionListener(this::clickJButtonActionPerformed);

        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(clickJButton)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(clickJButton)
                .addGap(64, 64, 64)
                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Yo manejo el clic del botón "Calculadora IMC".
     * Al presionarlo, abro la ventana de la calculadora y la hago visible.
     *
     * @param evt El evento de acción generado al hacer clic en el botón.
     */
    private void clickJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickJButtonActionPerformed

        // Yo creo una nueva instancia de la calculadora IMC y la muestro en pantalla
        CalculadoraIMC ventanaCalculadora = new CalculadoraIMC();
        ventanaCalculadora.setVisible(true);

    }//GEN-LAST:event_clickJButtonActionPerformed

    /**
     * Yo inicio la aplicación desde la ventana principal con el Look and Feel Nimbus.
     *
     * @param args Argumentos de la línea de comandos (no se utilizan).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Yo muestro la ventana principal en el hilo de eventos de Swing */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clickJButton;
    private javax.swing.JLabel jLabelNombre;
    // End of variables declaration//GEN-END:variables
}
